baseURL = "/"
defaultContentLanguage = "es"
languageCode = "fr-fr"
summaryLength = "10"
theme = "educenter-hugo"
title = "Qori"

[params]
author = "Ana Medina"
copyright = "Qori - Copyright &copy; 2020 [<img src=\"https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png\" alt=\"Licence Creative Commons\">](http://creativecommons.org/licenses/by-nc-sa/4.0/)"
description = "Qori est une société proposant des services à vos besoins"
email = "contact@qori.fr"
google_analitycs_id = "UA-59880117-2"
home = "Qori"
logo = "images/logo-w-sm.gif"
phone = "+33 (0) 7 80 97 35 25"

primary_color = "#cf1931"
nav_color = "#102f5e"
top_header = true

[params.contact]
enable = true
form_action = "https://calendly.com/qori"

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


[params.preloader]
enable = true
preloader = "images/logo-sm.gif"

[[params.social]]
title = "facebook"
link = "https://www.facebook.com/qori.france"
icon = "ti-facebook"

[[params.social]]
title = "messenger"
link = "http://m.me/qori.france"
icon = "ti-comments"

################################### Espanol language #####################################
[languages.es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/espanol"
weight = 1
# copyright
copyright = "Content is copyrighted &copy; 2020 by Qori [Licence Creative Commons **by-nc-sa**](http://creativecommons.org/licenses/by-nc-sa/4.0/); web site Theme from **[themefisher](https://themefisher.com)**"


[[languages.es.menu.main]]
URL = "about"
name = "Nosotros"
weight = 1

[[languages.es.menu.main]]
identifier = "estudia"
URL = "pages/estudia"
name = "Estudia en Francia"
weight = 2
[[languages.es.menu.main]]
parent = "estudia"
URL = "pages/estudia/estudios_superiores"
name = "Estudios Superiores"
weight = 1
[[languages.es.menu.main]]
parent = "estudia"
URL = "pages/estudia/frances"
name = "Lengua Francesa"
weight = 2
#[[languages.es.menu.main]]
#parent = "estudia"
#URL = "pages/estudia/carrera_universitaria"
#name = "Estudios Superiores"
#weight = 2

[[languages.es.menu.main]]
identifier = "traduccion"
URL = "pages/traduccion"
name = "Traducción"
weight = 4
[[languages.es.menu.main]]
parent = "traduccion"
URL = "pages/traduccion/comercial"
name = "Comercial"
weight = 1
[[languages.es.menu.main]]
parent = "traduccion"
URL = "pages/traduccion/informatica"
name = "Informática"
weight = 2
[[languages.es.menu.main]]
parent = "traduccion"
URL = "pages/traduccion/literaria"
name = "Literaria"
weight = 3
[[languages.es.menu.main]]
parent = "traduccion"
URL = "pages/traduccion/relectura"
name = "Relectura"
weight = 4
[[languages.es.menu.main]]
parent = "traduccion"
URL = "pages/traduccion/simple"
name = "Simple"
weight = 5

[[languages.es.menu.main]]
identifier = "interpretacion"
URL = "pages/interpretacion"
name = "Interpretación"
weight = 5
[[languages.es.menu.main]]
parent = "interpretacion"
URL = "pages/interpretacion/simultanea"
name = "Simultánea"
weight = 1
[[languages.es.menu.main]]
parent = "interpretacion"
URL = "pages/interpretacion/consecutiva"
name = "Consecutiva"
weight = 2

[[languages.es.menu.main]]
identifier = "asesorias"
URL = "pages/asesorias"
name = "Asesorías"
weight = 6
[[languages.es.menu.main]]
parent = "asesorias"
URL = "pages/asesorias/empleo"
name = "Búsqueda de empleo en Francia"
weight = 1

[[languages.es.menu.main]]
URL = "blog"
name = "Blog"
weight = 7

[[languages.es.menu.main]]
URL = "contact"
name = "Contact"
weight = 8

################################### French language #####################################
[languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 3
# copyright
copyright = "Contenu protégé par droit d'auteur &copy; 2020 pour Qori [Licence Creative Commons **by-nc-sa**](http://creativecommons.org/licenses/by-nc-sa/4.0/); thème du site web par **[themefisher](https://themefisher.com)**"


[[languages.fr.menu.main]]
URL = "about"
name = "A propos"
weight = 1

[[languages.fr.menu.main]]
identifier = "estudia"
URL = "pages/estudia"
name = "Etudes en France"
weight = 2
[[languages.fr.menu.main]]
parent = "estudia"
URL = "pages/estudia/frances"
name = "Langue Française"
weight = 1
[[languages.fr.menu.main]]
parent = "estudia"
URL = "pages/estudia/carrera_universitaria"
name = "Etudes supérieures"
weight = 2

[[languages.fr.menu.main]]
identifier = "traduccion"
URL = "pages/traduccion"
name = "Traduction"
weight = 4
[[languages.fr.menu.main]]
parent = "traduccion"
URL = "pages/traduccion/comercial"
name = "Commercial"
weight = 1
[[languages.fr.menu.main]]
parent = "traduccion"
URL = "pages/traduccion/informatica"
name = "Informatique"
weight = 2
[[languages.fr.menu.main]]
parent = "traduccion"
URL = "pages/traduccion/literaria"
name = "Litéraire"
weight = 3
[[languages.fr.menu.main]]
parent = "traduccion"
URL = "pages/traduccion/relectura"
name = "Relecture"
weight = 4
[[languages.fr.menu.main]]
parent = "traduccion"
URL = "pages/traduccion/simple"
name = "Simple"
weight = 5

[[languages.fr.menu.main]]
identifier = "interpretacion"
URL = "pages/interpretacion"
name = "Interprétation"
weight = 5
[[languages.fr.menu.main]]
parent = "interpretacion"
URL = "pages/interpretacion/simultanea"
name = "Simultanée"
weight = 1
[[languages.fr.menu.main]]
parent = "interpretacion"
URL = "pages/interpretacion/consecutiva"
name = "Consécutive"
weight = 2

[[languages.fr.menu.main]]
identifier = "asesorias"
URL = "pages/asesorias"
name = "Conseils"
weight = 6
[[languages.fr.menu.main]]
parent = "asesorias"
URL = "pages/asesorias/empleo"
name = "Recherche emploi en France"
weight = 1

[[languages.fr.menu.main]]
URL = "blog"
name = "Blog"
weight = 7

[[languages.fr.menu.main]]
URL = "contact"
name = "Contact"
weight = 8