baseURL = "/"
languageCode = "fr-fr"
summaryLength = "10"
theme = "educenter-hugo"
title = "Qori"

[menu]
[[menu.main]]
URL = "about"
name = "Nosotros"
weight = 1

[[menu.main]]
identifier = "estudia"
URL = "pages/estudia"
name = "Estudia en Francia"
weight = 2
[[menu.main]]
parent = "estudia"
URL = "pages/estudia/frances"
name = "Lengua Francesa"
weight = 1
[[menu.main]]
parent = "estudia"
URL = "pages/estudia/carrera_universitaria"
name = "Estudios Superiores"
weight = 2

[[menu.main]]
identifier = "traduccion"
URL = "pages/traduccion"
name = "Traducción"
weight = 4
[[menu.main]]
parent = "traduccion"
URL = "pages/traduccion/comercial"
name = "Comercial"
weight = 1
[[menu.main]]
parent = "traduccion"
URL = "pages/traduccion/informatica"
name = "Informática"
weight = 2
[[menu.main]]
parent = "traduccion"
URL = "pages/traduccion/literaria"
name = "Literaria"
weight = 3
[[menu.main]]
parent = "traduccion"
URL = "pages/traduccion/relectura"
name = "Relectura"
weight = 4
[[menu.main]]
parent = "traduccion"
URL = "pages/traduccion/simple"
name = "Simple"
weight = 5

[[menu.main]]
identifier = "interpretacion"
URL = "pages/interpretacion"
name = "Interpretación"
weight = 5
[[menu.main]]
parent = "interpretacion"
URL = "pages/interpretacion/simultanea"
name = "Simultánea"
weight = 1
[[menu.main]]
parent = "interpretacion"
URL = "pages/interpretacion/consecutiva"
name = "Consecutiva"
weight = 2

[[menu.main]]
identifier = "asesorias"
URL = "pages/asesorias"
name = "Asesorias"
weight = 6
[[menu.main]]
parent = "asesorias"
URL = "pages/asesorias/empleo"
name = "Búsqueda de empleo en Francia"
weight = 1

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 7

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 8

[params]
author = "Ana Medina"
copyright = "Qori - Copyright &copy; 2020"
description = "Qori est une société proposant des services à vos besoins"
email = "anamedina111@gmail.com"
#google_analitycs_id = "Your ID"
home = "Qori"
logo = "images/logo-w-sm.gif"
phone = "+33 6.. .. .. .."

primary_color = "#cf1931"
nav_color = "#102f5e"
top_header = true

[params.contact]
enable = false
form_action = "#"

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


[params.preloader]
enable = true
preloader = "Bienvenido! Qori"

[[params.social]]
URL = "https://www.facebook.com/"
icon = "ti-facebook"


################################### Espanol language #####################################
[Languages.es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/espanol"
weight = 1
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 3
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"

